package com.andye.warmod.warhead.client;

import com.andye.warmod.warhead.WarheadPayloadType;
import com.andye.warmod.warhead.client.render.BlastCloudLobe;
import com.andye.warmod.warhead.client.render.FireballLobe;
import com.andye.warmod.warhead.network.ClientboundWarheadImpactPayload;
import java.util.ArrayList;
import java.util.List;
import java.util.SplittableRandom;
import java.util.UUID;
import net.minecraft.world.phys.Vec3;

public final class ImpactVisualState {
	private final UUID warheadId;private final Vec3 impactPosition;private final long impactGameTime,visualSeed;private final float visualScale;private final WarheadPayloadType payloadType;private final WarheadClientVisualProfile profile;
	private final TerrainRingSampler terrainSampler;private final TerrainShockfrontField terrainShockfrontField;private final List<FireballLobe> fireballLobes;private final List<BlastCloudLobe> blastCloudLobes;
	private boolean initialBurstEmitted,secondaryBurstEmitted;private long lastContinuousParticleTick=Long.MIN_VALUE;private int emittedParticleCount;
	public ImpactVisualState(final UUID id,final Vec3 position,final long time,final long seed,final WarheadPayloadType payloadType,final float scale){this.warheadId=id;this.impactPosition=position;this.impactGameTime=time;this.visualSeed=seed;this.payloadType=payloadType;this.visualScale=scale;this.profile=WarheadClientVisualProfiles.get(payloadType,seed);this.terrainSampler=new TerrainRingSampler(position,seed);this.terrainShockfrontField=new TerrainShockfrontField(position,seed);this.fireballLobes=createFireballLobes(seed,profile);this.blastCloudLobes=createSmokeLobes(seed,profile);}
	public static ImpactVisualState fromPayload(final ClientboundWarheadImpactPayload p){return new ImpactVisualState(p.warheadId(),new Vec3(p.impactX(),p.impactY(),p.impactZ()),p.impactGameTime(),p.visualSeed(),p.payloadType(),p.impactVisualScale());}
	public UUID warheadId(){return warheadId;}public Vec3 impactPosition(){return impactPosition;}public long impactGameTime(){return impactGameTime;}public long visualSeed(){return visualSeed;}public float visualScale(){return visualScale;}public WarheadPayloadType payloadType(){return payloadType;}public WarheadClientVisualProfile profile(){return profile;}public TerrainRingSampler terrainSampler(){return terrainSampler;}public TerrainShockfrontField terrainShockfrontField(){return terrainShockfrontField;}public List<FireballLobe> fireballLobes(){return fireballLobes;}public List<BlastCloudLobe> blastCloudLobes(){return blastCloudLobes;}
	public double ageTicks(final long time,final double partial){return Math.max(0,time-impactGameTime)+Math.max(0,Math.min(1,partial));}public boolean isExpired(final long time,final double partial){double age=ageTicks(time,partial);return !Double.isFinite(age)||age>=profile.totalImpactLifetimeTicks();}
	boolean initialBurstEmitted(){return initialBurstEmitted;}void markInitialBurstEmitted(){initialBurstEmitted=true;}boolean secondaryBurstEmitted(){return secondaryBurstEmitted;}void markSecondaryBurstEmitted(){secondaryBurstEmitted=true;}long lastContinuousParticleTick(){return lastContinuousParticleTick;}void markContinuousParticleTick(final long t){lastContinuousParticleTick=t;}int emittedParticleCount(){return emittedParticleCount;}void recordParticleEmission(){emittedParticleCount++;}
	private static List<FireballLobe> createFireballLobes(final long seed,final WarheadClientVisualProfile p){SplittableRandom r=new SplittableRandom(seed^0x464952454C4F4245L);int count=p.nearFireballLobes();List<FireballLobe> list=new ArrayList<>(count);boolean nuclear=p.payloadType()==WarheadPayloadType.NUCLEAR;for(int i=0;i<count;i++){double fraction=i/(double)count;int band=fraction<.45?0:fraction<.80?1:2;double angle=r.nextDouble(0,Math.PI*2),radialFactor=band==0?Math.sqrt(r.nextDouble())*.42:band==1?r.nextDouble(.35,.72):r.nextDouble(.68,1.0);double width=nuclear?p.fireballWidth():60,height=nuclear?p.fireballHeight():84;double radial=radialFactor*width*.5;double y=Math.pow(r.nextDouble(),.82)*height;Vec3 offset=new Vec3(Math.cos(angle)*radial,y,Math.sin(angle)*radial);double base=nuclear?r.nextDouble(7,14):r.nextDouble(3,6.5);list.add(new FireballLobe(offset,r.nextDouble(0,nuclear?6:3),base,r.nextDouble(.5,1.15),r.nextDouble(.45,1.05),r.nextDouble(.4,nuclear?8:3.2),r.nextDouble(0,Math.PI*2),r.nextInt(8)));}return List.copyOf(list);}
	private static List<BlastCloudLobe> createSmokeLobes(final long seed,final WarheadClientVisualProfile p){SplittableRandom r=new SplittableRandom(seed^0x424C415354434C44L);int count=p.nearSmokeLobes();List<BlastCloudLobe> list=new ArrayList<>(count);boolean nuclear=p.payloadType()==WarheadPayloadType.NUCLEAR;for(int i=0;i<count;i++){boolean upper=nuclear?i>=count*4/10:i>=count/2;double angle=r.nextDouble(0,Math.PI*2);double radial=upper?r.nextDouble(nuclear?p.smokeCapWidth()*.10:2.5,nuclear?p.smokeCapWidth()*.50:11):r.nextDouble(.4,nuclear?p.smokeStemWidth()*.5:4.5);double y=upper?r.nextDouble(nuclear?p.maximumCloudHeight()*.58:18,nuclear?p.maximumCloudHeight()*.82:34):r.nextDouble(0,nuclear?p.maximumCloudHeight()*.68:25);boolean core=i%3!=0;int red=core?r.nextInt(18,43):r.nextInt(55,101),green=core?r.nextInt(20,47):r.nextInt(60,106),blue=core?r.nextInt(24,55):r.nextInt(68,116);float opacity=(float)(core?r.nextDouble(nuclear?.72:.46,nuclear?.88:.63):r.nextDouble(nuclear?.48:.28,nuclear?.70:.45));double radius=nuclear?(upper?r.nextDouble(12,24):r.nextDouble(8,16)):(upper?r.nextDouble(3,5.5):r.nextDouble(2.5,4.3));list.add(new BlastCloudLobe(new Vec3(Math.cos(angle)*radial,y,Math.sin(angle)*radial),radius,r.nextDouble(.8,1.2),r.nextDouble(1,nuclear?18:7),r.nextDouble(0,Math.PI*2),r.nextDouble(0,Math.PI*2),upper,red,green,blue,opacity));}return List.copyOf(list);}
}