package com.andye.warmod.radar.client.gui;

import com.andye.warmod.radar.client.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.network.chat.Component;

public final class RadarMapRenderer {
	private static final int BACKGROUND = 0xff05090b, MINOR_GRID = 0xff101a1f, MAJOR_GRID = 0xff1b2a31, X_AXIS = 0xff4a2721, Z_AXIS = 0xff1d3f43, LABEL = 0xff7f969d;
	private RadarMapRenderer() { }
	public static void render(final GuiGraphicsExtractor graphics, final ClientRadarState state, final RadarMapTransform transform, final double now, final int left, final int top, final int width, final int height) { graphics.fill(left, top, left + width, top + height, BACKGROUND); graphics.enableScissor(left, top, left + width, top + height); grid(graphics, Minecraft.getInstance().font, transform, left, top, width, height); for (ClientRadarTrack track : state.tracks()) RadarTrackRenderer.renderRoutes(graphics, track, transform, now, left, top, width, height, track.id().equals(state.selectedTrackId())); for (ClientRadarImpact impact : state.impacts()) RadarImpactRenderer.render(graphics, impact, transform, now, left, top, width, height); for (ClientRadarInterception event : state.interceptions()) RadarInterceptionRenderer.render(graphics,event,transform,now,left,top,width,height); for (ClientRadarTrack track : state.tracks()) RadarTrackRenderer.renderMarkers(graphics, track, transform, now, left, top, width, height, track.id().equals(state.selectedTrackId())); RadarPlayerRenderer.render(graphics, Minecraft.getInstance().font, Minecraft.getInstance().player, transform, left, top, width, height); graphics.disableScissor(); }
	public static void renderGrid(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final int left, final int top, final int width, final int height) { graphics.fill(left, top, left + width, top + height, BACKGROUND); graphics.enableScissor(left, top, left + width, top + height); grid(graphics, Minecraft.getInstance().font, transform, left, top, width, height); graphics.disableScissor(); }
	private static void grid(final GuiGraphicsExtractor graphics, final Font font, final RadarMapTransform transform, final int left, final int top, final int width, final int height) { double majorSpacing = powerOfTwoAtLeast(transform.blocksPerPixel() * 80.0); double minorSpacing = majorSpacing / 4.0; if (minorSpacing / transform.blocksPerPixel() < 16.0) minorSpacing = majorSpacing / 2.0; if (minorSpacing / transform.blocksPerPixel() < 16.0) minorSpacing = majorSpacing; double minimumX = transform.worldX(left, left, width), maximumX = transform.worldX(left + width, left, width), minimumZ = transform.worldZ(top, top, height), maximumZ = transform.worldZ(top + height, top, height); drawGridLines(graphics, transform, minimumX, maximumX, minimumZ, maximumZ, majorSpacing, minorSpacing, left, top, width, height); drawAxes(graphics, transform, minimumX, maximumX, minimumZ, maximumZ, left, top, width, height); drawLabels(graphics, font, transform, minimumX, maximumX, minimumZ, maximumZ, majorSpacing, left, top, width, height); }
	private static void drawGridLines(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final double minimumX, final double maximumX, final double minimumZ, final double maximumZ, final double majorSpacing, final double minorSpacing, final int left, final int top, final int width, final int height) { int minorMultiple = (int)Math.round(majorSpacing / minorSpacing); if (minorSpacing < majorSpacing) { for (int count = 0; count < 128; count++) { double x = firstLine(minimumX, minorSpacing) + count * minorSpacing; if (x > maximumX) break; if (Math.round(x / minorSpacing) % minorMultiple != 0) vertical(graphics, transform, x, left, top, width, height, MINOR_GRID); } for (int count = 0; count < 128; count++) { double z = firstLine(minimumZ, minorSpacing) + count * minorSpacing; if (z > maximumZ) break; if (Math.round(z / minorSpacing) % minorMultiple != 0) horizontal(graphics, transform, z, left, top, width, height, MINOR_GRID); } } for (int count = 0; count < 128; count++) { double x = firstLine(minimumX, majorSpacing) + count * majorSpacing; if (x > maximumX) break; vertical(graphics, transform, x, left, top, width, height, MAJOR_GRID); } for (int count = 0; count < 128; count++) { double z = firstLine(minimumZ, majorSpacing) + count * majorSpacing; if (z > maximumZ) break; horizontal(graphics, transform, z, left, top, width, height, MAJOR_GRID); } }
	private static void drawAxes(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final double minimumX, final double maximumX, final double minimumZ, final double maximumZ, final int left, final int top, final int width, final int height) { if (minimumX <= 0.0 && maximumX >= 0.0) vertical(graphics, transform, 0.0, left, top, width, height, X_AXIS); if (minimumZ <= 0.0 && maximumZ >= 0.0) horizontal(graphics, transform, 0.0, left, top, width, height, Z_AXIS); }
	private static void drawLabels(final GuiGraphicsExtractor graphics, final Font font, final RadarMapTransform transform, final double minimumX, final double maximumX, final double minimumZ, final double maximumZ, final double spacing, final int left, final int top, final int width, final int height) { if (spacing / transform.blocksPerPixel() >= 70.0) { for (int count = 0; count < 128; count++) { double x = firstLine(minimumX, spacing) + count * spacing; if (x > maximumX) break; int screenX = (int)Math.round(transform.screenX(x, left, width)); graphics.text(font, Component.literal("X " + formatCoordinate(x)), screenX + 3, top + height - 10, LABEL); } for (int count = 0; count < 128; count++) { double z = firstLine(minimumZ, spacing) + count * spacing; if (z > maximumZ) break; int screenY = (int)Math.round(transform.screenY(z, top, height)); graphics.text(font, Component.literal("Z " + formatCoordinate(z)), left + 3, screenY + 2, LABEL); } } graphics.text(font, Component.literal("N"), left + width - 12, top + 5, 0xffb9d9df); }
	private static void vertical(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final double worldX, final int left, final int top, final int width, final int height, final int color) { int x = (int)Math.round(transform.screenX(worldX, left, width)); if (x >= left && x < left + width) graphics.fill(x, top, x + 1, top + height, color); }
	private static void horizontal(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final double worldZ, final int left, final int top, final int width, final int height, final int color) { int y = (int)Math.round(transform.screenY(worldZ, top, height)); if (y >= top && y < top + height) graphics.fill(left, y, left + width, y + 1, color); }
	private static double firstLine(final double minimum, final double spacing) { return Math.ceil(minimum / spacing) * spacing; }
	private static double powerOfTwoAtLeast(final double value) { double spacing = 16.0; while (spacing < value) spacing *= 2.0; return spacing; }
	private static String formatCoordinate(final double value) { long rounded = Math.round(value), absolute = Math.abs(rounded); if (absolute >= 1000 && rounded % 1000 == 0) return (rounded / 1000) + "k"; return Long.toString(rounded); }
}