package com.andye.warmod.radar.client.gui;

import com.andye.warmod.radar.RadarTrackKind;
import com.andye.warmod.radar.client.ClientRadarTrack;
import com.andye.warmod.warhead.WarheadPayloadType;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.util.Mth;
import net.minecraft.world.phys.Vec3;

public final class RadarTrackRenderer {
	private RadarTrackRenderer() { }
	public static void renderRoutes(final GuiGraphicsExtractor graphics, final ClientRadarTrack track, final RadarMapTransform transform, final double now, final int left, final int top, final int width, final int height, final boolean selected) { boolean nuclear = track.snapshot().payloadType() == WarheadPayloadType.NUCLEAR; int completed = nuclear ? 0xffff5a32 : 0xffffad32, projected = nuclear ? 0x886b281f : 0x8870521d; if (!track.carrierRoute().isEmpty()) { double duration = track.carrierDuration(); if (track.snapshot().terminalPlan().isPresent()) RadarPolylineRenderer.drawRouteRange(graphics, track.carrierRoute(), duration, 0.0, duration, transform, left, top, width, height, (completed & 0x00ffffff) | 0x99000000, 1, false); else { double current = Mth.clamp(track.carrierElapsed(now), 0.0, duration); drawCompleted(graphics, track.carrierRoute(), duration, 0.0, current, transform, left, top, width, height, completed, selected); RadarPolylineRenderer.drawRouteRange(graphics, track.carrierRoute(), duration, current, duration, transform, left, top, width, height, projected, 1, true); } } if (!track.terminalRoute().isEmpty()) { double duration = track.terminalDuration(), current = Mth.clamp(track.terminalElapsed(now), 0.0, duration); drawCompleted(graphics, track.terminalRoute(), duration, 0.0, current, transform, left, top, width, height, completed, selected); RadarPolylineRenderer.drawRouteRange(graphics, track.terminalRoute(), duration, current, duration, transform, left, top, width, height, projected, 1, true); } }
	public static void renderMarkers(final GuiGraphicsExtractor graphics, final ClientRadarTrack track, final RadarMapTransform transform, final double now, final int left, final int top, final int width, final int height, final boolean selected) { int color = track.snapshot().payloadType() == WarheadPayloadType.NUCLEAR ? 0xffff5a32 : 0xffffad32; drawLaunch(graphics, transform, track.launch(), left, top, width, height); drawTarget(graphics, transform, track.target(), left, top, width, height, color); drawMissile(graphics, track, transform, now, left, top, width, height, color, selected); }
	private static void drawCompleted(final GuiGraphicsExtractor graphics, final java.util.List<Vec3> points, final double duration, final double from, final double to, final RadarMapTransform transform, final int left, final int top, final int width, final int height, final int color, final boolean selected) { if (selected) RadarPolylineRenderer.drawRouteRange(graphics, points, duration, from, to, transform, left, top, width, height, 0x66ffffff, 3, false); RadarPolylineRenderer.drawRouteRange(graphics, points, duration, from, to, transform, left, top, width, height, color, 2, false); }
	private static void drawMissile(final GuiGraphicsExtractor graphics, final ClientRadarTrack track, final RadarMapTransform transform, final double now, final int left, final int top, final int width, final int height, final int color, final boolean selected) { Vec3 position = track.position(now), velocity = track.velocity(now); double x = transform.screenX(position.x, left, width), y = transform.screenY(position.z, top, height); if (x < left || x >= left + width || y < top || y >= top + height) { x = Math.max(left + 4, Math.min(left + width - 5, x)); y = Math.max(top + 4, Math.min(top + height - 5, y)); } double length = Math.hypot(velocity.x, velocity.z), dx = length < 1.0E-6 ? 0.0 : velocity.x / length, dy = length < 1.0E-6 ? 1.0 : velocity.z / length, sideX = -dy, sideY = dx; boolean terminal = track.snapshot().terminalPlan().isPresent() || track.snapshot().kind() == RadarTrackKind.DIRECT_WARHEAD; double nose = terminal ? 4.0 : 5.0, tail = terminal ? 2.5 : 3.5, halfWidth = terminal ? 2.5 : 3.5, tipX = x + dx * nose, tipY = y + dy * nose, aX = x - dx * tail + sideX * halfWidth, aY = y - dy * tail + sideY * halfWidth, bX = x - dx * tail - sideX * halfWidth, bY = y - dy * tail - sideY * halfWidth; if (selected) { RadarPolylineRenderer.drawSegment(graphics, tipX, tipY, aX, aY, left, top, width, height, 0xffffffff, 2); RadarPolylineRenderer.drawSegment(graphics, aX, aY, bX, bY, left, top, width, height, 0xffffffff, 2); RadarPolylineRenderer.drawSegment(graphics, bX, bY, tipX, tipY, left, top, width, height, 0xffffffff, 2); } RadarPolylineRenderer.drawSegment(graphics, tipX, tipY, aX, aY, left, top, width, height, color, 1); RadarPolylineRenderer.drawSegment(graphics, aX, aY, bX, bY, left, top, width, height, color, 1); RadarPolylineRenderer.drawSegment(graphics, bX, bY, tipX, tipY, left, top, width, height, color, 1); }
	private static void drawLaunch(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final Vec3 position, final int left, final int top, final int width, final int height) { int x = (int)Math.round(transform.screenX(position.x, left, width)), y = (int)Math.round(transform.screenY(position.z, top, height)); RadarPolylineRenderer.drawRing(graphics, x, y, 3.0, left, top, width, height, 0xff66d9ff, 1, 32); }
	private static void drawTarget(final GuiGraphicsExtractor graphics, final RadarMapTransform transform, final Vec3 position, final int left, final int top, final int width, final int height, final int color) { int x = (int)Math.round(transform.screenX(position.x, left, width)), y = (int)Math.round(transform.screenY(position.z, top, height)); RadarPolylineRenderer.drawSegment(graphics, x - 5, y, x + 5, y, left, top, width, height, color, 1); RadarPolylineRenderer.drawSegment(graphics, x, y - 5, x, y + 5, left, top, width, height, color, 1); }
}