package com.andye.warmod.block;
import com.andye.warmod.block.entity.MissileSiloBlockEntity;import com.andye.warmod.item.ModItems;import java.util.*;import net.minecraft.core.BlockPos;import net.minecraft.core.Direction;import net.minecraft.server.level.ServerLevel;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.block.Block;import net.minecraft.world.level.block.Blocks;import net.minecraft.world.level.block.state.BlockState;
public final class MissileSiloGuidanceFrameStructure {
 private static final Set<String> TEARING_DOWN=new HashSet<>();private MissileSiloGuidanceFrameStructure(){}
 public static double maximumGuidanceError(int tier){return switch(Math.max(0,Math.min(3,tier))){case 1->50.0;case 2->25.0;case 3->0.0;default->100.0;};}
 public static BlockPos position(BlockPos centre,Direction facing,int tier,MissileSiloGuidanceFrameLayer layer,MissileSiloGuidanceFramePart part){return centre.offset(part.rotatedOffset(facing)).above((tier-1)*2+(layer==MissileSiloGuidanceFrameLayer.LOWER?1:2));}
 public static int installedTier(ServerLevel level,BlockPos centre,Direction facing){int found=0;for(int tier=1;tier<=3;tier++){if(!complete(level,centre,facing,tier))break;found=tier;}return found;}
 public static boolean complete(ServerLevel level,BlockPos centre,Direction facing,int tier){for(var layer:MissileSiloGuidanceFrameLayer.values())for(var part:MissileSiloGuidanceFramePart.values()){BlockState s=level.getBlockState(position(centre,facing,tier,layer,part));if(!s.is(ModBlocks.MISSILE_SILO_GUIDANCE_FRAME)||s.getValue(MissileSiloGuidanceFrameBlock.TIER)!=tier||s.getValue(MissileSiloGuidanceFrameBlock.LAYER)!=layer||s.getValue(MissileSiloGuidanceFrameBlock.PART)!=part||s.getValue(MissileSiloGuidanceFrameBlock.FACING)!=facing)return false;}return true;}
 public static boolean installNext(ServerLevel level,BlockPos centre,Direction facing,Player player){if(!(level.getBlockEntity(centre) instanceof MissileSiloBlockEntity silo)||!silo.siloId().equals(silo.siloId()))return false;int tier=installedTier(level,centre,facing)+1;if(tier>3)return fail(player,"All three guidance tiers are installed");for(var layer:MissileSiloGuidanceFrameLayer.values()){BlockPos shaft=centre.above((tier-1)*2+(layer==MissileSiloGuidanceFrameLayer.LOWER?1:2));if(!level.getBlockState(shaft).isAir())return fail(player,"Guidance shaft is obstructed at "+shaft.toShortString());for(var part:MissileSiloGuidanceFramePart.values()){BlockPos p=position(centre,facing,tier,layer,part);if(level.isOutsideBuildHeight(p)||!level.getWorldBorder().isWithinBounds(p)||level.getBlockEntity(p)!=null||!level.getBlockState(p).canBeReplaced()||(player!=null&&!level.mayInteract(player,p)))return fail(player,"Guidance frame obstructed at "+p.toShortString());}}
 List<BlockPos>placed=new ArrayList<>();try{for(var layer:MissileSiloGuidanceFrameLayer.values())for(var part:MissileSiloGuidanceFramePart.values()){BlockPos p=position(centre,facing,tier,layer,part);BlockState state=ModBlocks.MISSILE_SILO_GUIDANCE_FRAME.defaultBlockState().setValue(MissileSiloGuidanceFrameBlock.TIER,tier).setValue(MissileSiloGuidanceFrameBlock.LAYER,layer).setValue(MissileSiloGuidanceFrameBlock.PART,part).setValue(MissileSiloGuidanceFrameBlock.FACING,facing);if(!level.setBlock(p,state,Block.UPDATE_ALL))throw new IllegalStateException();placed.add(p);}silo.sync();return true;}catch(RuntimeException ex){for(BlockPos p:placed)level.setBlock(p,Blocks.AIR.defaultBlockState(),Block.UPDATE_ALL);return fail(player,"Guidance frame placement failed atomically");}}
 public static void teardownFromPart(ServerLevel level,BlockPos pos,BlockState state,boolean drops){if(!state.is(ModBlocks.MISSILE_SILO_GUIDANCE_FRAME))return;Direction facing=state.getValue(MissileSiloGuidanceFrameBlock.FACING);int tier=state.getValue(MissileSiloGuidanceFrameBlock.TIER);int yOffset=(tier-1)*2+(state.getValue(MissileSiloGuidanceFrameBlock.LAYER)==MissileSiloGuidanceFrameLayer.LOWER?1:2);BlockPos centre=state.getValue(MissileSiloGuidanceFrameBlock.PART).resolveCentre(pos.below(yOffset),facing);teardown(level,centre,facing,tier,drops);}
 public static void teardown(ServerLevel level,BlockPos centre,Direction facing,int fromTier,boolean drops){String key=level.dimension().identifier()+":"+centre.asLong();synchronized(TEARING_DOWN){if(!TEARING_DOWN.add(key))return;}try{int highest=installedTier(level,centre,facing);int removed=0;for(int tier=fromTier;tier<=3;tier++){boolean any=false;for(var layer:MissileSiloGuidanceFrameLayer.values())for(var part:MissileSiloGuidanceFramePart.values()){BlockPos p=position(centre,facing,tier,layer,part);if(level.getBlockState(p).is(ModBlocks.MISSILE_SILO_GUIDANCE_FRAME)){level.setBlock(p,Blocks.AIR.defaultBlockState(),Block.UPDATE_ALL);any=true;}}if(any&&tier<=highest)removed++;}if(drops)for(int i=0;i<removed;i++)Block.popResource(level,centre,new ItemStack(ModItems.MISSILE_SILO_GUIDANCE_FRAME));if(level.getBlockEntity(centre)instanceof MissileSiloBlockEntity silo)silo.sync();}finally{synchronized(TEARING_DOWN){TEARING_DOWN.remove(key);}}}
 private static boolean fail(Player p,String message){if(p!=null)p.sendSystemMessage(net.minecraft.network.chat.Component.literal(message));return false;}
}