package com.andye.warmod.block;
import com.mojang.serialization.MapCodec;
import java.util.function.BiConsumer;
import net.minecraft.core.BlockPos;import net.minecraft.core.Direction;import net.minecraft.server.level.ServerLevel;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.Explosion;import net.minecraft.world.level.Level;import net.minecraft.world.level.block.Block;import net.minecraft.world.level.block.state.BlockBehaviour;import net.minecraft.world.level.block.state.BlockState;import net.minecraft.world.level.block.state.StateDefinition;import net.minecraft.world.level.block.state.properties.EnumProperty;import net.minecraft.world.level.block.state.properties.IntegerProperty;import net.minecraft.world.level.block.state.properties.Property;import net.minecraft.world.phys.shapes.CollisionContext;import net.minecraft.world.phys.shapes.Shapes;import net.minecraft.world.phys.shapes.VoxelShape;
public final class MissileSiloGuidanceFrameBlock extends Block {
 public static final MapCodec<MissileSiloGuidanceFrameBlock> CODEC=simpleCodec(MissileSiloGuidanceFrameBlock::new);public static final EnumProperty<MissileSiloGuidanceFramePart> PART=EnumProperty.create("part",MissileSiloGuidanceFramePart.class);public static final EnumProperty<MissileSiloGuidanceFrameLayer> LAYER=EnumProperty.create("layer",MissileSiloGuidanceFrameLayer.class);public static final IntegerProperty TIER=IntegerProperty.create("tier",1,3);public static final Property<Direction> FACING=net.minecraft.world.level.block.HorizontalDirectionalBlock.FACING;
 private static final VoxelShape CORNER=Shapes.or(Block.box(2,0,2,6,16,6),Block.box(4,3,4,16,6,7),Block.box(4,10,4,16,13,7));private static final VoxelShape EDGE=Shapes.or(Block.box(6,0,6,10,16,10),Block.box(0,4,6,16,7,10),Block.box(0,11,6,16,14,10));
 public MissileSiloGuidanceFrameBlock(BlockBehaviour.Properties p){super(p);registerDefaultState(stateDefinition.any().setValue(PART,MissileSiloGuidanceFramePart.NORTH).setValue(LAYER,MissileSiloGuidanceFrameLayer.LOWER).setValue(TIER,1).setValue(FACING,Direction.NORTH));}
 @Override protected MapCodec<? extends Block> codec(){return CODEC;}@Override protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){b.add(PART,LAYER,TIER,FACING);}@Override protected VoxelShape getShape(BlockState s,net.minecraft.world.level.BlockGetter l,BlockPos p,CollisionContext c){return s.getValue(PART).corner()?CORNER:EDGE;}
 @Override public BlockState playerWillDestroy(Level level,BlockPos pos,BlockState state,Player player){if(level instanceof ServerLevel server)MissileSiloGuidanceFrameStructure.teardownFromPart(server,pos,state,true);return state;}@Override public void playerDestroy(Level l,Player p,BlockPos pos,BlockState s,net.minecraft.world.level.block.entity.BlockEntity be,ItemStack tool){}
 @Override protected void onExplosionHit(BlockState state,ServerLevel level,BlockPos pos,Explosion explosion,BiConsumer<ItemStack,BlockPos> hit){MissileSiloGuidanceFrameStructure.teardownFromPart(level,pos,state,true);}
}