package com.andye.warmod.menu;
import com.andye.warmod.block.MissileSiloStructure;import com.andye.warmod.block.entity.MissileSiloBlockEntity;import com.andye.warmod.silo.MissilePayloadItems;import com.andye.warmod.silo.MissileSiloConstants;import java.util.UUID;import net.minecraft.core.BlockPos;import net.minecraft.server.level.ServerLevel;import net.minecraft.world.SimpleContainer;import net.minecraft.world.entity.player.Inventory;import net.minecraft.world.entity.player.Player;import net.minecraft.world.inventory.AbstractContainerMenu;import net.minecraft.world.inventory.Slot;import net.minecraft.world.item.ItemStack;import org.jspecify.annotations.Nullable;
public final class MissileSiloMenu extends AbstractContainerMenu {private static final int SILO_SLOT=0,PLAYER_START=1,PLAYER_END=37;private final BlockPos centre;private final UUID siloId;private final @Nullable MissileSiloBlockEntity silo;
 public MissileSiloMenu(int id,Inventory inventory,ModMenus.SiloOpeningData data){this(id,inventory,resolve(inventory,data),data.centre(),data.siloId());}
 public MissileSiloMenu(int id,Inventory inventory,MissileSiloBlockEntity silo){this(id,inventory,silo,silo.getBlockPos(),silo.siloId());}
 private MissileSiloMenu(int id,Inventory playerInventory,@Nullable MissileSiloBlockEntity silo,BlockPos centre,UUID siloId){super(ModMenus.MISSILE_SILO,id);this.centre=centre;this.siloId=siloId;this.silo=silo;var container=silo==null?new SimpleContainer(1):silo;checkContainerSize(container,1);addSlot(new Slot(container,0,46,52){@Override public boolean mayPlace(ItemStack stack){return MissilePayloadItems.isMissile(stack)&&container.canPlaceItem(0,stack);}@Override public boolean mayPickup(Player player){return MissileSiloMenu.this.silo==null||MissileSiloMenu.this.silo.extractionAllowed();}@Override public int getMaxStackSize(){return MissileSiloConstants.MAX_MISSILES;}});addStandardInventorySlots(playerInventory,107,150);}
 private static @Nullable MissileSiloBlockEntity resolve(Inventory inventory,ModMenus.SiloOpeningData data){return inventory.player.level().getBlockEntity(data.centre())instanceof MissileSiloBlockEntity silo&&silo.siloId().equals(data.siloId())?silo:null;}
 public BlockPos centre(){return centre;}public UUID siloId(){return siloId;}public @Nullable MissileSiloBlockEntity silo(){return silo;}
 @Override public boolean stillValid(Player player){if(silo==null||player.level()!=silo.getLevel()||!silo.siloId().equals(siloId)||player.distanceToSqr(centre.getX()+.5,centre.getY()+.5,centre.getZ()+.5)>64)return false;return !(player.level() instanceof ServerLevel server)||MissileSiloStructure.isComplete(server,centre,silo.facing());}
 @Override public ItemStack quickMoveStack(Player player,int index){Slot slot=getSlot(index);if(!slot.hasItem())return ItemStack.EMPTY;ItemStack source=slot.getItem(),copy=source.copy();if(index==SILO_SLOT){if(!slot.mayPickup(player)||!moveItemStackTo(source,PLAYER_START,PLAYER_END,true))return ItemStack.EMPTY;}else{if(!MissilePayloadItems.isMissile(source)||!moveItemStackTo(source,SILO_SLOT,SILO_SLOT+1,false))return ItemStack.EMPTY;}if(source.isEmpty())slot.setByPlayer(ItemStack.EMPTY);else slot.setChanged();return copy;}
}