package com.andye.warmod.warhead.client.render;

import com.andye.warmod.warhead.WarheadPayloadType;import com.andye.warmod.warhead.WarheadVisualMath;import com.andye.warmod.warhead.client.WarheadClientVisualProfile;import com.mojang.blaze3d.vertex.PoseStack;import com.mojang.blaze3d.vertex.VertexConsumer;import java.util.List;import net.minecraft.util.Mth;import net.minecraft.world.phys.Vec3;import org.joml.Quaternionf;import org.joml.Vector3f;
public final class BlastCloudRenderer {
	private BlastCloudRenderer(){}
	public static void render(final PoseStack.Pose pose,final VertexConsumer buffer,final double age,final float visualScale,final WarheadClientVisualProfile p,final List<BlastCloudLobe> lobes,final WarheadMesh.Lod lod,final Quaternionf camera){if(age<p.smokeStartTick()||age>=p.cloudDissipationEndTick()||lobes==null||lobes.isEmpty())return;int limit=lod==WarheadMesh.Lod.NEAR?p.nearSmokeLobes():lod==WarheadMesh.Lod.MEDIUM?p.mediumSmokeLobes():p.farSmokeLobes();limit=Math.min(limit,lobes.size());double fade=Math.pow(1-WarheadVisualMath.clamp((age-p.cloudRiseEndTick())/(double)Math.max(1,p.cloudDissipationEndTick()-p.cloudRiseEndTick()),0,1),.72);double scale=p.payloadType()==WarheadPayloadType.NUCLEAR?1.0:Mth.clamp(visualScale,.55F,1.45F);double lodRadius=lod==WarheadMesh.Lod.FAR?1.55:lod==WarheadMesh.Lod.MEDIUM?1.18:1.0;for(int visible=0;visible<limit;visible++){int index=(int)((long)visible*lobes.size()/limit);BlastCloudLobe l=lobes.get(index);if(age<l.spawnTick())continue;double rawLocal=WarheadVisualMath.clamp((age-l.spawnTick())/Math.max(1,l.growthTicks()),0,1);double local=smooth(rawLocal);double after=Math.max(0,age-l.spawnTick()-l.growthTicks());Vec3 center=center(l,p,age,(float)scale);float radius=(float)(l.baseRadius()*Mth.lerp(local,.16,1.0)*scale*lodRadius*(1+.075*Math.sin(l.phase()+after*.031)));double appear=smooth(rawLocal/.24);float alpha=(float)(l.opacity()*appear*fade);billboard(pose,buffer,center,radius,l.rotation()+after*.0015,l.red(),l.green(),l.blue(),alpha,camera);}}
	public static Vec3 center(final BlastCloudLobe l,final WarheadClientVisualProfile profile,final double age,final float scale){if(age<l.spawnTick())return new Vec3(Double.NaN,Double.NaN,Double.NaN);double raw=WarheadVisualMath.clamp((age-l.spawnTick())/Math.max(1,l.growthTicks()),0,1),local=smooth(raw),after=Math.max(0,age-l.spawnTick()-l.growthTicks());Vec3 result=switch(l.flowRole()){case STEM->stemCenter(l,profile,local,after);case CAP_CORE->capCoreCenter(l,profile,raw,after);case CAP_ROLLING_RIM->rimCenter(l,profile,raw,age);};return result.scale(scale);}
	private static Vec3 stemCenter(final BlastCloudLobe l,final WarheadClientVisualProfile p,final double local,final double after){Vec3 linear=l.originOffset().lerp(l.finalOffset(),local);double inward=1.0-.18*local;double amplitude=Math.max(1.0,Math.min(5.0,p.smokeStemWidth()*.065));double turbulence=amplitude*(.25+.75*local);double x=linear.x*inward+Math.sin(l.lateralPhase()+local*7.0+after*.018)*turbulence;double z=linear.z*inward+Math.cos(l.lateralPhase()*.83+local*6.0+after*.016)*turbulence;double continuedRise=Math.min(p.maximumCloudHeight()*.08,after*.018*l.riseFactor());return new Vec3(x,linear.y+continuedRise,z);}
	private static Vec3 capCoreCenter(final BlastCloudLobe l,final WarheadClientVisualProfile p,final double local,final double after){Vec3 stemTop=new Vec3(0,p.maximumCloudHeight()*.60,0);Vec3 emerged=new Vec3(l.originOffset().x*.25,p.maximumCloudHeight()*.74,l.originOffset().z*.25);Vec3 spread=new Vec3(l.finalOffset().x,Math.max(l.finalOffset().y,p.maximumCloudHeight()*.82),l.finalOffset().z);Vec3 center;if(local<.30)center=cubic(stemTop,emerged,local/.30);else if(local<.75)center=cubic(emerged,spread,(local-.30)/.45);else center=cubic(spread,l.finalOffset(),(local-.75)/.25);double driftAngle=after*.0012+l.flowPhase();double drift=.025*p.smokeCapWidth()*Math.sin(after*.009+l.phase());return center.add(Math.cos(driftAngle)*drift,Math.sin(after*.008+l.lateralPhase())*p.maximumCloudHeight()*.008,Math.sin(driftAngle)*drift);}
	private static Vec3 rimCenter(final BlastCloudLobe l,final WarheadClientVisualProfile p,final double local,final double age){Vec3 stemTop=new Vec3(0,p.maximumCloudHeight()*.58,0);Vec3 capTop=new Vec3(l.finalOffset().x*.15,p.maximumCloudHeight()*.79,l.finalOffset().z*.15);Vec3 outerTop=new Vec3(l.finalOffset().x,Math.max(l.finalOffset().y,p.maximumCloudHeight()*.78),l.finalOffset().z);Vec3 growthPath=local<.30?cubic(stemTop,capTop,local/.30):cubic(capTop,outerTop,(local-.30)/.70);double circulationAge=Math.max(0,age-l.spawnTick()-l.growthTicks()*.65);double circulationAngle=l.flowPhase()+circulationAge*l.circulationRate();double tubeRadius=p.smokeCapWidth()*(.09+.025*Math.sin(l.phase()));double verticalTube=p.maximumCloudHeight()*(.055+.018*Math.cos(l.phase()));double radial=p.smokeCapWidth()*l.capRadialFraction()+Math.cos(circulationAngle)*tubeRadius;double y=p.maximumCloudHeight()*l.capVerticalFraction()+Math.sin(circulationAngle)*verticalTube;double azimuth=l.rotation()+circulationAge*Math.abs(l.circulationRate())*.12;Vec3 circulating=new Vec3(Math.cos(azimuth)*radial,y,Math.sin(azimuth)*radial);double circulationBlend=smooth((local-.52)/.33);return growthPath.lerp(circulating,circulationBlend);}
	private static Vec3 cubic(final Vec3 a,final Vec3 b,final double value){return a.lerp(b,smooth(value));}
	private static void billboard(final PoseStack.Pose p,final VertexConsumer b,final Vec3 c,final float radius,final double rotation,final int r,final int g,final int bl,final float alpha,final Quaternionf camera){float cos=Mth.cos((float)rotation),sin=Mth.sin((float)rotation),ux=cos*radius,uy=sin*radius,vx=-sin*radius,vy=cos*radius;int a=Mth.clamp((int)(alpha*255),0,255);vertex(p,b,c,-ux-vx,-uy-vy,0,1,r,g,bl,a,camera);vertex(p,b,c,-ux+vx,-uy+vy,0,0,r,g,bl,a,camera);vertex(p,b,c,ux+vx,uy+vy,1,0,r,g,bl,a,camera);vertex(p,b,c,ux-vx,uy-vy,1,1,r,g,bl,a,camera);}
	private static void vertex(final PoseStack.Pose p,final VertexConsumer b,final Vec3 c,final float x,final float y,final float u,final float v,final int r,final int g,final int bl,final int a,final Quaternionf camera){Vector3f o=new Vector3f(x,y,0).rotate(camera),n=new Vector3f(0,0,1).rotate(camera);b.addVertex(p,(float)c.x+o.x,(float)c.y+o.y,(float)c.z+o.z).setColor(r,g,bl,a).setUv(u,v).setOverlay(0).setLight(0xA000A0).setNormal(p,n.x,n.y,n.z);}
	private static double smooth(final double v){double t=WarheadVisualMath.clamp(v,0,1);return t*t*(3-2*t);}
}