package com.andye.warmod.warhead.client.render;

import com.andye.warmod.warhead.WarheadPayloadType;
import com.andye.warmod.warhead.WarheadVisualMath;
import com.andye.warmod.warhead.client.WarheadClientVisualProfile;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import java.util.List;
import net.minecraft.util.Mth;
import net.minecraft.world.phys.Vec3;
import org.joml.Quaternionf;
import org.joml.Vector3f;

public final class ImpactFireballRenderer {
	private ImpactFireballRenderer(){}
	public static void renderHot(final PoseStack.Pose pose,final VertexConsumer buffer,final double age,final float visualScale,final WarheadClientVisualProfile profile,final List<FireballLobe> lobes,final WarheadMesh.Lod lod,final Quaternionf camera){render(pose,buffer,age,visualScale,profile,lobes,lod,true,camera);}
	public static void renderCooling(final PoseStack.Pose pose,final VertexConsumer buffer,final double age,final float visualScale,final WarheadClientVisualProfile profile,final List<FireballLobe> lobes,final WarheadMesh.Lod lod,final Quaternionf camera){render(pose,buffer,age,visualScale,profile,lobes,lod,false,camera);}
	private static void render(final PoseStack.Pose pose,final VertexConsumer buffer,final double age,final float visualScale,final WarheadClientVisualProfile p,final List<FireballLobe> lobes,final WarheadMesh.Lod lod,final boolean hot,final Quaternionf camera){if(age<p.fireballGrowthStartTick()||age>=p.fireballCoolingEndTick()||lobes==null)return;int limit=lod==WarheadMesh.Lod.NEAR?p.nearFireballLobes():lod==WarheadMesh.Lod.MEDIUM?p.mediumFireballLobes():p.farFireballLobes();limit=Math.min(limit,lobes.size());double growth=smooth((age-p.fireballGrowthStartTick())/(double)Math.max(1,p.fireballGrowthEndTick()-p.fireballGrowthStartTick()));double cooling=WarheadVisualMath.clamp((age-p.fireballHoldEndTick())/(double)Math.max(1,p.fireballCoolingEndTick()-p.fireballHoldEndTick()),0,1);if(hot&&cooling>=.96)return;if(!hot&&age<p.fireballHoldEndTick()-Math.max(4,(p.fireballHoldEndTick()-p.fireballGrowthEndTick())*.2))return;double geometryScale=p.payloadType()==WarheadPayloadType.NUCLEAR?1.0:Mth.clamp(visualScale,.45F,1.5F);for(int i=0;i<limit;i++){FireballLobe l=lobes.get(i);if(age<l.spawnDelayTicks())continue;double hotAlpha=(1-Math.pow(cooling,1.35))*.94,coolAlpha=smooth(cooling/.22)*Math.pow(1-cooling,.55)*.80;double alpha=(hot?hotAlpha:coolAlpha)*(1-i/(double)Math.max(1,limit)*.25)*l.opacityMultiplier();if(alpha<=.01)continue;Vec3 radial=new Vec3(l.baseOffset().x,0,l.baseOffset().z);Vec3 direction=radial.lengthSqr()<1E-6?new Vec3(Math.cos(l.rotation()),0,Math.sin(l.rotation())):radial.normalize();Vec3 center=l.baseOffset().scale(growth*geometryScale).add(direction.scale(l.horizontalDrift()*growth)).add(0,p.fireballRise()*growth*.18*l.riseSpeed(),0);float radius=(float)(l.baseRadius()*l.expansionMultiplier()*(.18+.82*growth)*geometryScale);int red=hot?255:Mth.lerpInt((float)cooling,220,76),green=hot?Mth.lerpInt((float)cooling,246,112):Mth.lerpInt((float)cooling,126,78),blue=hot?Mth.lerpInt((float)cooling,180,35):Mth.lerpInt((float)cooling,46,34);FireballAtlas.Uv uv=FireballAtlas.frame(age,l,p.fireballCoolingEndTick());billboard(pose,buffer,center,radius,l.rotation(),red,green,blue,alpha,hot?0xF000F0:0xA000A0,camera,uv.u0(),uv.u1(),uv.v0(),uv.v1());}}
	private static void billboard(final PoseStack.Pose pose,final VertexConsumer b,final Vec3 c,final float radius,final double rotation,final int red,final int green,final int blue,final double alpha,final int light,final Quaternionf camera,final float u0,final float u1,final float v0,final float v1){float cos=Mth.cos((float)rotation),sin=Mth.sin((float)rotation),ux=cos*radius,uy=sin*radius,vx=-sin*radius,vy=cos*radius;int a=Mth.clamp((int)(alpha*255),0,255);vertex(pose,b,c,-ux-vx,-uy-vy,u0,v1,red,green,blue,a,light,camera);vertex(pose,b,c,-ux+vx,-uy+vy,u0,v0,red,green,blue,a,light,camera);vertex(pose,b,c,ux+vx,uy+vy,u1,v0,red,green,blue,a,light,camera);vertex(pose,b,c,ux-vx,uy-vy,u1,v1,red,green,blue,a,light,camera);}
	private static void vertex(final PoseStack.Pose p,final VertexConsumer b,final Vec3 c,final float x,final float y,final float u,final float v,final int r,final int g,final int bl,final int a,final int light,final Quaternionf camera){Vector3f o=new Vector3f(x,y,0).rotate(camera),n=new Vector3f(0,0,1).rotate(camera);b.addVertex(p,(float)c.x+o.x,(float)c.y+o.y,(float)c.z+o.z).setColor(r,g,bl,a).setUv(u,v).setOverlay(0).setLight(light).setNormal(p,n.x,n.y,n.z);}
	private static double smooth(final double value){double t=WarheadVisualMath.clamp(value,0,1);return t*t*(3-2*t);}
}